issues:
  exclude-rules:
    - path: pkg/middleware/account_uuid.go
      text: "SA4006:"
      linters:
        - staticcheck
    - path: pkg/proxy/proxy_integration_test.go
      linters:
        - bodyclose
linters:
  enable:
    - bodyclose
    - deadcode
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - golint
    - unconvert
    # - scopelint
    - maligned
    - misspell
    - prealloc
    #- gosec

  disable:
    - errcheck
    - ineffassign
    - scopelint
